spring:
  application:
    name: xiaozhiMed
  data:
    mongodb:
      uri: mongodb://localhost:27017/chat_memory_db

  datasource:
    url: jdbc:mysql://localhost:3306/sky_take_out?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 123456

mybatis:
  configuration:
    map-underscore-to-camel-case: true

langchain4j:
  open-ai:
    chat-model:
      # TODO  改为在系统环境变量中使用
      api-key: sk-86cd7810a53440cf8d1d555bf16ed3d3
      model-name: deepseek-v3
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
  community:
    dashscope:
      chat-model:
        api-key: sk-86cd7810a53440cf8d1d555bf16ed3d3
        model-name: qwen-plus

logging:
  level:
    root: info


